# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Tue Nov 18 11:55:17 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(715, 639)
        MainWindow.setMinimumSize(QtCore.QSize(680, 520))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 0, 691, 601))
        self.tabWidget.setMinimumSize(QtCore.QSize(640, 480))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.mainTab = QtGui.QWidget()
        self.mainTab.setObjectName(_fromUtf8("mainTab"))
        self.groupBox = QtGui.QGroupBox(self.mainTab)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 681, 571))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 10, 361, 251))
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Sunken)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("../CPW/0.png")))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName(_fromUtf8("label"))
        self.wEdit = QtGui.QLineEdit(self.groupBox)
        self.wEdit.setGeometry(QtCore.QRect(120, 20, 71, 21))
        self.wEdit.setObjectName(_fromUtf8("wEdit"))
        self.hEdit = QtGui.QLineEdit(self.groupBox)
        self.hEdit.setGeometry(QtCore.QRect(250, 160, 91, 21))
        self.hEdit.setObjectName(_fromUtf8("hEdit"))
        self.eEdit = QtGui.QLineEdit(self.groupBox)
        self.eEdit.setGeometry(QtCore.QRect(130, 160, 51, 21))
        self.eEdit.setObjectName(_fromUtf8("eEdit"))
        self.tEdit = QtGui.QLineEdit(self.groupBox)
        self.tEdit.setGeometry(QtCore.QRect(250, 90, 91, 21))
        self.tEdit.setObjectName(_fromUtf8("tEdit"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(350, 90, 16, 16))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.sEdit = QtGui.QLineEdit(self.groupBox)
        self.sEdit.setGeometry(QtCore.QRect(170, 50, 61, 21))
        self.sEdit.setObjectName(_fromUtf8("sEdit"))
        self.tgEdit = QtGui.QLineEdit(self.groupBox)
        self.tgEdit.setGeometry(QtCore.QRect(90, 210, 109, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tgEdit.setFont(font)
        self.tgEdit.setObjectName(_fromUtf8("tgEdit"))
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(200, 20, 16, 16))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(350, 160, 16, 16))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(240, 50, 16, 16))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_50 = QtGui.QLabel(self.groupBox)
        self.label_50.setGeometry(QtCore.QRect(60, 210, 29, 16))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(390, 200, 251, 160))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_28 = QtGui.QLabel(self.groupBox_3)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 2, 2, 1, 1)
        self.f0Edit = QtGui.QLineEdit(self.groupBox_3)
        self.f0Edit.setObjectName(_fromUtf8("f0Edit"))
        self.gridLayout.addWidget(self.f0Edit, 0, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_3)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout.addWidget(self.label_32, 1, 2, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox_3)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout.addWidget(self.label_34, 3, 2, 1, 1)
        self.label_44 = QtGui.QLabel(self.groupBox_3)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout.addWidget(self.label_44, 0, 2, 1, 1)
        self.CEdit = QtGui.QLineEdit(self.groupBox_3)
        self.CEdit.setObjectName(_fromUtf8("CEdit"))
        self.gridLayout.addWidget(self.CEdit, 2, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_3)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 2, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_3)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout.addWidget(self.label_29, 1, 0, 1, 1)
        self.REdit = QtGui.QLineEdit(self.groupBox_3)
        self.REdit.setObjectName(_fromUtf8("REdit"))
        self.gridLayout.addWidget(self.REdit, 3, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_3)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout.addWidget(self.label_30, 0, 0, 1, 1)
        self.LEdit = QtGui.QLineEdit(self.groupBox_3)
        self.LEdit.setObjectName(_fromUtf8("LEdit"))
        self.gridLayout.addWidget(self.LEdit, 1, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox_3)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout.addWidget(self.label_33, 3, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(390, 360, 251, 165))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 2, 0, 1, 2)
        self.frEdit = QtGui.QLineEdit(self.groupBox_4)
        self.frEdit.setObjectName(_fromUtf8("frEdit"))
        self.gridLayout_5.addWidget(self.frEdit, 3, 2, 1, 1)
        self.qeEdit = QtGui.QLineEdit(self.groupBox_4)
        self.qeEdit.setObjectName(_fromUtf8("qeEdit"))
        self.gridLayout_5.addWidget(self.qeEdit, 1, 2, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_4)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_5.addWidget(self.label_36, 0, 0, 1, 1)
        self.qlEdit = QtGui.QLineEdit(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abadi MT Condensed Extra Bold"))
        font.setBold(False)
        font.setWeight(50)
        self.qlEdit.setFont(font)
        self.qlEdit.setObjectName(_fromUtf8("qlEdit"))
        self.gridLayout_5.addWidget(self.qlEdit, 2, 2, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox_4)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_5.addWidget(self.label_35, 3, 0, 1, 2)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_4)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_5.addWidget(self.label_40, 1, 3, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox_4)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_5.addWidget(self.label_41, 0, 3, 1, 1)
        self.label_39 = QtGui.QLabel(self.groupBox_4)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_5.addWidget(self.label_39, 2, 3, 1, 1)
        self.qiEdit = QtGui.QLineEdit(self.groupBox_4)
        self.qiEdit.setObjectName(_fromUtf8("qiEdit"))
        self.gridLayout_5.addWidget(self.qiEdit, 0, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_4)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_5.addWidget(self.label_31, 3, 3, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 410, 341, 151))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.lambdaLabel = QtGui.QLabel(self.groupBox_5)
        self.lambdaLabel.setGeometry(QtCore.QRect(170, 30, 164, 21))
        self.lambdaLabel.setMinimumSize(QtCore.QSize(164, 21))
        self.lambdaLabel.setMaximumSize(QtCore.QSize(160, 16777215))
        self.lambdaLabel.setObjectName(_fromUtf8("lambdaLabel"))
        self.alfaLabel = QtGui.QLabel(self.groupBox_5)
        self.alfaLabel.setGeometry(QtCore.QRect(170, 117, 164, 21))
        self.alfaLabel.setMinimumSize(QtCore.QSize(160, 21))
        self.alfaLabel.setText(_fromUtf8(""))
        self.alfaLabel.setObjectName(_fromUtf8("alfaLabel"))
        self.lambdaLabel_2 = QtGui.QLabel(self.groupBox_5)
        self.lambdaLabel_2.setGeometry(QtCore.QRect(17, 30, 145, 21))
        self.lambdaLabel_2.setMinimumSize(QtCore.QSize(132, 21))
        self.lambdaLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lambdaLabel_2.setObjectName(_fromUtf8("lambdaLabel_2"))
        self.eeffLabel_2 = QtGui.QLabel(self.groupBox_5)
        self.eeffLabel_2.setGeometry(QtCore.QRect(17, 88, 145, 21))
        self.eeffLabel_2.setMinimumSize(QtCore.QSize(132, 21))
        self.eeffLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.eeffLabel_2.setObjectName(_fromUtf8("eeffLabel_2"))
        self.eeffLabel = QtGui.QLabel(self.groupBox_5)
        self.eeffLabel.setGeometry(QtCore.QRect(170, 88, 164, 21))
        self.eeffLabel.setMinimumSize(QtCore.QSize(160, 21))
        self.eeffLabel.setText(_fromUtf8(""))
        self.eeffLabel.setObjectName(_fromUtf8("eeffLabel"))
        self.kineticLabel = QtGui.QLabel(self.groupBox_5)
        self.kineticLabel.setGeometry(QtCore.QRect(170, 59, 164, 21))
        self.kineticLabel.setMinimumSize(QtCore.QSize(160, 21))
        self.kineticLabel.setText(_fromUtf8(""))
        self.kineticLabel.setObjectName(_fromUtf8("kineticLabel"))
        self.alfaLabel_2 = QtGui.QLabel(self.groupBox_5)
        self.alfaLabel_2.setGeometry(QtCore.QRect(17, 117, 145, 21))
        self.alfaLabel_2.setMinimumSize(QtCore.QSize(130, 21))
        self.alfaLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.alfaLabel_2.setObjectName(_fromUtf8("alfaLabel_2"))
        self.kineticLabel_2 = QtGui.QLabel(self.groupBox_5)
        self.kineticLabel_2.setGeometry(QtCore.QRect(17, 59, 145, 21))
        self.kineticLabel_2.setMinimumSize(QtCore.QSize(132, 21))
        self.kineticLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kineticLabel_2.setObjectName(_fromUtf8("kineticLabel_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 30, 252, 163))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 3, 2, 1, 1)
        self.fEdit = QtGui.QLineEdit(self.groupBox_2)
        self.fEdit.setObjectName(_fromUtf8("fEdit"))
        self.gridLayout_2.addWidget(self.fEdit, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 1, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 2, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 0, 2, 1, 1)
        self.llEdit = QtGui.QLineEdit(self.groupBox_2)
        self.llEdit.setObjectName(_fromUtf8("llEdit"))
        self.gridLayout_2.addWidget(self.llEdit, 1, 1, 1, 1)
        self.clEdit = QtGui.QLineEdit(self.groupBox_2)
        self.clEdit.setObjectName(_fromUtf8("clEdit"))
        self.gridLayout_2.addWidget(self.clEdit, 2, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 1, 0, 1, 1)
        self.z0Edit = QtGui.QLineEdit(self.groupBox_2)
        self.z0Edit.setObjectName(_fromUtf8("z0Edit"))
        self.gridLayout_2.addWidget(self.z0Edit, 3, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 3, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 2, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 250, 341, 151))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_18 = QtGui.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(280, 22, 43, 21))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(6, 90, 47, 21))
        self.label_11.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.tcEdit = QtGui.QLineEdit(self.groupBox_6)
        self.tcEdit.setGeometry(QtCore.QRect(61, 90, 209, 21))
        self.tcEdit.setObjectName(_fromUtf8("tcEdit"))
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(280, 56, 43, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(280, 90, 43, 21))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lEdit = QtGui.QLineEdit(self.groupBox_6)
        self.lEdit.setGeometry(QtCore.QRect(61, 22, 209, 21))
        self.lEdit.setObjectName(_fromUtf8("lEdit"))
        self.rhoEdit = QtGui.QLineEdit(self.groupBox_6)
        self.rhoEdit.setGeometry(QtCore.QRect(61, 56, 209, 21))
        self.rhoEdit.setObjectName(_fromUtf8("rhoEdit"))
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setGeometry(QtCore.QRect(6, 56, 47, 21))
        self.label_12.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_6 = QtGui.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(6, 22, 47, 21))
        self.label_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_37 = QtGui.QLabel(self.groupBox_6)
        self.label_37.setGeometry(QtCore.QRect(0, 120, 55, 20))
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.groupBox_6)
        self.label_38.setGeometry(QtCore.QRect(290, 120, 16, 16))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.ccEdit = QtGui.QLineEdit(self.groupBox_6)
        self.ccEdit.setGeometry(QtCore.QRect(65, 120, 201, 21))
        self.ccEdit.setObjectName(_fromUtf8("ccEdit"))
        self.closeButton = QtGui.QPushButton(self.groupBox)
        self.closeButton.setGeometry(QtCore.QRect(510, 530, 106, 32))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.runButton = QtGui.QPushButton(self.groupBox)
        self.runButton.setGeometry(QtCore.QRect(400, 530, 106, 32))
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.tabWidget.addTab(self.mainTab, _fromUtf8(""))
        self.plotTab = QtGui.QWidget()
        self.plotTab.setObjectName(_fromUtf8("plotTab"))
        self.layoutWidget = QtGui.QWidget(self.plotTab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 631, 451))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.plotBox = QtGui.QGroupBox(self.layoutWidget)
        self.plotBox.setObjectName(_fromUtf8("plotBox"))
        self.plotWidget = MPL_Widget(self.plotBox)
        self.plotWidget.setGeometry(QtCore.QRect(10, 30, 601, 371))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setMinimumSize(QtCore.QSize(1, 1))
        self.plotWidget.setMaximumSize(QtCore.QSize(801, 16777215))
        self.plotWidget.setAutoFillBackground(True)
        self.plotWidget.setObjectName(_fromUtf8("plotWidget"))
        self.verticalLayout.addWidget(self.plotBox)
        self.plotBtn = QtGui.QPushButton(self.layoutWidget)
        self.plotBtn.setObjectName(_fromUtf8("plotBtn"))
        self.verticalLayout.addWidget(self.plotBtn)
        self.tabWidget.addTab(self.plotTab, _fromUtf8(""))
        self.widget = QtGui.QWidget()
        self.widget.setObjectName(_fromUtf8("widget"))
        self.tabWidget.addTab(self.widget, _fromUtf8(""))
        self.dataTab = QtGui.QWidget()
        self.dataTab.setObjectName(_fromUtf8("dataTab"))
        self.tableWidget = QtGui.QTableWidget(self.dataTab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 10, 471, 181))
        self.tableWidget.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        self.label_43 = QtGui.QLabel(self.dataTab)
        self.label_43.setGeometry(QtCore.QRect(0, 200, 281, 231))
        self.label_43.setFrameShape(QtGui.QFrame.Box)
        self.label_43.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.tabWidget.addTab(self.dataTab, _fromUtf8(""))
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.closeButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.ccEdit, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.runButton.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Input", None))
        self.wEdit.setText(_translate("MainWindow", "6.0e-6", None))
        self.hEdit.setText(_translate("MainWindow", "500e-6", None))
        self.eEdit.setText(_translate("MainWindow", "11.6", None))
        self.tEdit.setText(_translate("MainWindow", "1.0e-7", None))
        self.label_16.setText(_translate("MainWindow", "m", None))
        self.sEdit.setText(_translate("MainWindow", "3.0e-6", None))
        self.tgEdit.setText(_translate("MainWindow", "1.00E-07", None))
        self.label_20.setText(_translate("MainWindow", "m", None))
        self.label_17.setText(_translate("MainWindow", "m", None))
        self.label_15.setText(_translate("MainWindow", "m", None))
        self.label_50.setToolTip(_translate("MainWindow", "Dielectric Loss (all loss)", None))
        self.label_50.setText(_translate("MainWindow", "Tgδ ", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "With Loss", None))
        self.label_28.setText(_translate("MainWindow", "F", None))
        self.label_32.setText(_translate("MainWindow", "H", None))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p>Ω</p></body></html>", None))
        self.label_44.setText(_translate("MainWindow", "Hz", None))
        self.label_27.setText(_translate("MainWindow", "C =", None))
        self.label_29.setText(_translate("MainWindow", "L =", None))
        self.label_30.setText(_translate("MainWindow", "f =", None))
        self.label_33.setText(_translate("MainWindow", "R =", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Result", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">Q load  =</span></p></body></html>", None))
        self.label_36.setText(_translate("MainWindow", "Qi   =", None))
        self.label_35.setText(_translate("MainWindow", "f r  =", None))
        self.label_8.setText(_translate("MainWindow", "Q ext =", None))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p>x10<span style=\" vertical-align:super;\">3</span></p></body></html>", None))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p>x10<span style=\" vertical-align:super;\">3</span></p></body></html>", None))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">x10</span><span style=\" color:#ff0000; vertical-align:super;\">3</span></p></body></html>", None))
        self.label_31.setText(_translate("MainWindow", "Hz", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Calculated Parameters", None))
        self.lambdaLabel.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.lambdaLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">λ</span><span style=\" font-size:14pt; vertical-align:sub;\">0</span><span style=\" font-size:14pt;\"> = </span></p></body></html>", None))
        self.eeffLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">ε</span><span style=\" font-size:14pt; vertical-align:sub;\">eff</span><span style=\" font-size:14pt;\"> = </span></p></body></html>", None))
        self.alfaLabel_2.setText(_translate("MainWindow", "<html><head/><body><p>Dielectric Loss (α) = </p></body></html>", None))
        self.kineticLabel_2.setText(_translate("MainWindow", "<html><head/><body><p>L Kinetic   = </p></body></html>", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Without Loss", None))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p>Ω</p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "f0 =", None))
        self.label_22.setText(_translate("MainWindow", "H/m", None))
        self.label_24.setText(_translate("MainWindow", "F/m", None))
        self.label_19.setText(_translate("MainWindow", "Hz", None))
        self.label_21.setText(_translate("MainWindow", "Ll =", None))
        self.label_25.setText(_translate("MainWindow", "Z0 =", None))
        self.label_23.setText(_translate("MainWindow", "Cl =", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Circuit Parameters", None))
        self.label_18.setText(_translate("MainWindow", "m", None))
        self.label_11.setText(_translate("MainWindow", "Tc= ", None))
        self.tcEdit.setText(_translate("MainWindow", "9", None))
        self.label_14.setText(_translate("MainWindow", "Ohm.m", None))
        self.label_13.setText(_translate("MainWindow", "K", None))
        self.lEdit.setText(_translate("MainWindow", "0.01127", None))
        self.rhoEdit.setText(_translate("MainWindow", "2.0e-8", None))
        self.label_12.setText(_translate("MainWindow", "ρ(Tc)= ", None))
        self.label_6.setToolTip(_translate("MainWindow", "CPW length", None))
        self.label_6.setText(_translate("MainWindow", "length =", None))
        self.label_37.setText(_translate("MainWindow", "Cc = ", None))
        self.label_38.setText(_translate("MainWindow", "F", None))
        self.ccEdit.setText(_translate("MainWindow", "1e-15", None))
        self.closeButton.setText(_translate("MainWindow", "Close", None))
        self.runButton.setText(_translate("MainWindow", "Run", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainTab), _translate("MainWindow", "CPW Designer", None))
        self.plotBox.setTitle(_translate("MainWindow", "Plot", None))
        self.plotBtn.setText(_translate("MainWindow", "Plot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plotTab), _translate("MainWindow", "Plot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Other", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Al", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Al", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nb", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nb", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Nb", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tickness (nm)", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "rho(Tc)(Ohm.m)", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tc(K)", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Reference", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "60", None))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "4.61e-9", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "1.23", None))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "Measured lab", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "150", None))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "3.34e-9", None))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "1.23", None))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "Measure lab", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "100", None))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "2.00e-8", None))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "9", None))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "?", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "150", None))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "0.58e-7", None))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "8.67", None))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "Yale", None))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "190", None))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "0.28e-7", None))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "8.97", None))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("MainWindow", "Yale", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">CONSTANTS</span></p><p><span style=\" font-size:10pt;\">C = 299792458 m / s</span></p><p><span style=\" font-size:10pt;\">E</span><span style=\" font-size:10pt; vertical-align:sub;\">0</span><span style=\" font-size:10pt;\"> = 8.8541878 x 10</span><span style=\" font-size:10pt; vertical-align:super;\">-12</span><span style=\" font-size:10pt;\"> F/m </span></p><p><span style=\" font-size:10pt;\">U</span><span style=\" font-size:10pt; vertical-align:sub;\">0</span><span style=\" font-size:10pt;\"> = 1.25664 x 10</span><span style=\" font-size:10pt; vertical-align:super;\">-06</span><span style=\" font-size:10pt;\"> H/m </span></p><p><span style=\" font-size:10pt;\">ε</span><span style=\" font-size:10pt; vertical-align:sub;\">0</span><span style=\" font-size:10pt;\"> =1 </span></p><p><span style=\" font-size:10pt;\">R </span><span style=\" font-size:10pt; vertical-align:sub;\">load</span><span style=\" font-size:10pt;\"> = 50 Ohm</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), _translate("MainWindow", "Data", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

from mpl_pyqt4_widget import MPL_Widget
